# --- COMA specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True


runner: "episode"

buffer_size: 100000
batch_size_run: 1
batch_size: 128

# update the target network every {} training steps
target_update_interval_or_tau: 10000

lr: 0.0000003 # ORIG HAD 3 ZEROS 

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False


# use COMA
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
standardise_returns: True
standardise_rewards: True

hidden_dim: 164

use_rnn: False
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
entropy_coef: 0.01 # ORIG had 2
q_nstep: 1  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
critic_type: coma_critic

name: "coma"
t_max: 20050000
