# --- IQL specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 0.9
epsilon_finish: 0.05
epsilon_anneal_time: 2450000
evaluation_epsilon: 0.0
runner: "episode"

buffer_size: 10000

# update the target network every {} episodes
target_update_interval_or_tau: 5000


obs_agent_id: False
obs_last_action: False
obs_individual_obs: False

# use the Q_Learner to train

agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: False
double_q: False
use_rnn: False
mixer: # Mixer becomes None

name: "iql"
