# --- IQL NS specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 0.95
epsilon_finish: 0.05
epsilon_anneal_time: 1700000
evaluation_epsilon: 0.0

runner: "episode"

buffer_size: 450000

# update the target network every {} episodes
target_update_interval_or_tau: 5200


obs_agent_id: False
obs_last_action: False
obs_individual_obs: True

# use the Q_Learner to train
mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "q"
learner: "q_learner"
standardise_returns: False
standardise_rewards: False
double_q: False
use_rnn: False
mixer: # Mixer becomes None

name: "iql_ns"
