# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: False

runner: "episode"

buffer_size: 10000
batch_size_run: 1
batch_size: 64

# update the target network every {} training steps
target_update_interval_or_tau: 400

lr: 0.0005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.01
use_rnn: False
standardise_returns: False
standardise_rewards: False
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 4
eps_clip: 0.2
name: "mappo"

t_max: 20050000
